<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/06/30 18:08:30

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=127.0.0.1;dbname=jobeet',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
