<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/06/30 18:08:30
sfConfig::add(array(
  'mod_default_enabled' => true,
  'mod_default_view_class' => 'sfPHP',
  'mod_default_is_internal' => false,
));
