<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/07/13 23:24:15
sfConfig::add(array(
  'mod_job_enabled' => true,
  'mod_job_view_class' => 'sfPHP',
  'mod_job_is_internal' => false,
));
