all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=127.0.0.1;dbname=jobeet';unix_socket=/Applications/MAMP/tmp/mysql/mysql.sock'
      username: root
      password: root
