<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/06/30 18:08:29
sfConfig::add(array(
  'mod_job_enabled' => true,
  'mod_job_view_class' => 'sfPHP',
  'mod_job_is_internal' => false,
));
